services:

  # Backend
  backend-dev:
    build:
      context: ./backend
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src  # Sync the source code
    stop_grace_period: 1s

  backend-prod:
    build:
      context: ./backend
      target: prod
    ports:
      - "8080:8080"
    env_file:
      - path: ./backend/.env.prod
        required: false

  backend-test:
    build:
      context: ./backend
      target: test

  # Frontend
  frontend-dev:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Sync the source code
      - /app/node_modules  # Don't sync the node_modules

  frontend-preview:
    build:
      context: ./frontend
      target: preview
    ports:
      - "3000:3000"

  frontend-prod:
    build:
      context: ./frontend
      target: prod
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "8443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro