services:

  # Backend
  backend-dev:
    build:
      context: ./backend
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src  # Sync the source code
    stop_grace_period: 1s

  backend-prod:
    build:
      context: ./backend
      target: prod
    ports:
      - "8080:8080"

  backend-test:
    build:
      context: ./backend
      target: test

  # Frontend
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Don't copy the node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8080

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"