name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            rm -rf /LeetLog
            git clone https://github.com/EmperorOwl/LeetLog.git
            cd LeetLog
            docker compose down
            export ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            export MONGO_URI=${{ secrets.MONGO_URI }}
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            export FRONTEND_URL=${{ secrets.VPS_IP }}
            docker compose up backend-prod frontend-prod --build -d
